// <auto-generated />
using System;
using Dispatch.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dispatch.Api.Migrations
{
    [DbContext(typeof(DispatchDbContext))]
    partial class DispatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dispatch.Api.Data.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_comments_ticket_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Dispatch.Api.Data.ProgressNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<long?>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_progress_notes");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_progress_notes_ticket_id_created_at");

                    b.ToTable("progress_notes", (string)null);
                });

            modelBuilder.Entity("Dispatch.Api.Data.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseContainer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_container");

                    b.Property<string>("ConfigPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("MaxParallel")
                        .HasColumnType("integer")
                        .HasColumnName("max_parallel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Org")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org");

                    b.Property<string>("ReposJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("repos_json");

                    b.Property<string>("Workspace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workspace");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_name");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Dispatch.Api.Data.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<DateTime>("AskedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asked_at");

                    b.Property<long?>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_questions_run_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_questions_ticket_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("Dispatch.Api.Data.Run", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("exit_code");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<bool>("SpecSubmitted")
                        .HasColumnType("boolean")
                        .HasColumnName("spec_submitted");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_runs");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_runs_status");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("ix_runs_one_active_per_ticket")
                        .HasFilter("status IN ('pending', 'running')");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("Dispatch.Api.Data.RunEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.HasKey("Id")
                        .HasName("pk_run_events");

                    b.HasIndex("RunId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("ix_run_events_run_id_seq");

                    b.ToTable("run_events", (string)null);
                });

            modelBuilder.Entity("Dispatch.Api.Data.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ClaudeSessionId")
                        .HasColumnType("text")
                        .HasColumnName("claude_session_id");

                    b.Property<string>("Container")
                        .HasColumnType("text")
                        .HasColumnName("container");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Spec")
                        .HasColumnType("text")
                        .HasColumnName("spec");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowState")
                        .HasColumnType("jsonb")
                        .HasColumnName("workflow_state");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_token");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("ix_tickets_project_id_status");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Dispatch.Api.Data.Comment", b =>
                {
                    b.HasOne("Dispatch.Api.Data.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Dispatch.Api.Data.ProgressNote", b =>
                {
                    b.HasOne("Dispatch.Api.Data.Ticket", "Ticket")
                        .WithMany("ProgressNotes")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_progress_notes_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Dispatch.Api.Data.Question", b =>
                {
                    b.HasOne("Dispatch.Api.Data.Ticket", "Ticket")
                        .WithMany("Questions")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Dispatch.Api.Data.Run", b =>
                {
                    b.HasOne("Dispatch.Api.Data.Ticket", "Ticket")
                        .WithMany("Runs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_runs_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Dispatch.Api.Data.RunEvent", b =>
                {
                    b.HasOne("Dispatch.Api.Data.Run", "Run")
                        .WithMany("Events")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_events_runs_run_id");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Dispatch.Api.Data.Ticket", b =>
                {
                    b.HasOne("Dispatch.Api.Data.Project", "Project")
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dispatch.Api.Data.Project", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Dispatch.Api.Data.Run", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Dispatch.Api.Data.Ticket", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ProgressNotes");

                    b.Navigation("Questions");

                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
